use_frameworks!

platform :ios, '8.0'

target 'GDBase_Example' do
  pod 'GDBase', :path => '../'

  target 'GDBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
